### ISSUE TITLE
SCM Federator polling does not appear to be working

### ISSUE THREAD

**Issue by tjdurden** [surevine/federated-scm#8]
Pre-reqs:
There is an existing project/repo in Stash, configured in the gateway as an outbound repo to be shared across an existing destination. Project repo has been shared already, confirmed as working.

Replication Steps:
Push a new change to the existing Stash repo (new file etc).
Wait until SCM Federator polling frequency reached.

At present, the SCM Federator polling does not appear to be taking effect / working.
Expecting the git bundle to be dropped into the destination URL (folder on disk) at next polling interval.

**Comment by martin-hewitt** [comment]
This was an issue to do with the presence (or lack thereof) of `mock` feature flags that were expected in the properties file, but have been removed during the shift to production. 044924d8fd6887cf4ab134b545ff5984a1239022 adds in a `try...catch` to the areas where these are expected, and defaults to false.
