### ISSUE TITLE
API request being dropped when sending updated repo to GitLab

### ISSUE THREAD

**Issue by tjdurden** [surevine/federated-scm#9]
Updated an existing repo in Stash, pulled the bundle to local, when uploading to GitLab it failed, throwing an error in /var/tmp/federated-scm.log - relating to:

GitlabCreateMergeRequestCommand:71 - Could not connect to REST service http://*******//api/v3/projects/17/merge_requests
javax.ws.rs.ProcessingException: Unable to invoke request
Caused by: java.net.SocketTimeoutException: Read timed out
at java.net.SocketInputStream.socketRead0(Native Method)

**Comment by martin-hewitt** [comment]
Closed in 5885296
